theme: jekyll-theme-cayman
title: ADA DRACO Website
description: A template website for ADA DRACO project
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
